ProjetoAnkiUnivesp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.generic.base import View
from core import views
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    url(r'^$', views.index, name="index"),     
    url(r'^contato/$', views.contact, name="contact"),
    url(r'^entrar/$', LoginView.as_view(template_name='login.html'), name='login'), 
    url(r'^sair/$', LogoutView.as_view(next_page = 'index'), name='logout'),  
    url(r'^ajuda/$', views.help, name="help"),
    url(r'^arquivo/$', views.file, name="file"), 
    url(r'^projeto/$', views.project, name="project"),
    url(r'^config_tentativa/$', views.create_attempt, name="config_tentativa"),
    url(r'^tentativa/$', views.list_attempt, name="list_attempt"),
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^questoes/', include('core.urls', namespace='core')),   
    # url(r'^questoes/$', views.list_question, name="list_question"),   
    url(r'^materias/$', views.list_theme, name="list_theme"),   
    url(r'^admin/', admin.site.urls),
    #teste
    url(r'^readText/$',views.readText, name="readText"),
    
]

accounts/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views

app_name = 'accounts'


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^alterar-dados/$', views.update_user, name='update_user'),
    url(r'^alterar-senha/$', views.update_password, name='update_password'),
    url(r'^registro/$', views.register, name='register')
]

core/urls.py
from django.urls import path

from .views import list_question, create_question, update_question, delete_question, list_theme, create_theme, delete_theme, update_theme
from django.conf.urls.static import static
from django.conf import settings
app_name = "core"

urlpatterns = [
    path('', list_question, name='list_question'),
    path('new', create_question, name='create_question'),
    path('update/<int:id>/', update_question, name='update_question'),
    path('delete/<int:id>/', delete_question, name='delete_question'),
    path('theme', list_theme, name='list_theme'),
    path('newTheme', create_theme, name='create_theme'),
    path('updateTheme/<int:id>/', update_theme, name='update_theme'),
    path('deleteTheme/<int:id>/', delete_theme, name='delete_theme'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from django.db import models
from accounts.models import User

# Create your models here.

class Category(models.Model):
    description = models.CharField(max_length=60, verbose_name='Categoria')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        db_table = 'category'

    def __str__(self):
        return self.description

class Theme(models.Model):
    description = models.CharField(max_length=250,verbose_name='Tema')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Categoria', default=0)

    class Meta:
        db_table = 'theme'
    
    def __str__(self):
        return self.description

    # def __init__(self, *args, **kwargs):
    #     super(Theme, self).__init__(*args, **kwargs)
    #     #self.fields["user"].value = 2
    #     print(User.id)

class Question(models.Model):
    description = models.CharField(max_length=250, null=False, verbose_name='Questão')
    answer = models.CharField(max_length=500, verbose_name='Resposta')
    image = models.TextField(null=True, verbose_name='Imagem')
    public = models.BooleanField(verbose_name='Publica')
    created_at = models.DateTimeField(auto_now_add=True)
    theme = models.ForeignKey(Theme, on_delete=models.CASCADE, verbose_name='Tema')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='usuários')

    class Meta:
        db_table = 'questions'
    
    def __str__(self):
        return self.description

class Difficults_options(models.IntegerChoices):
    EASY = 1
    MEDIUM = 2
    DIFFICULT = 3 

class Attempt(models.Model):
    attempt_number = models.IntegerField(null=False)
    attempt_date = models.DateTimeField(auto_now_add=True)
    got_it_right = models.BooleanField(verbose_name='acertou')
    difficult = models.IntegerField(choices=Difficults_options.choices, verbose_name='Dificuldade')
    question = models.ForeignKey(Question, on_delete=models.CASCADE,verbose_name='Questão')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='usuários')

    class Meta:
        db_table = 'attempts'

    def __str__(self):
        return self.question.description        
    

core/forms.py
from email import message
import this
from django import forms
from django.core.mail import send_mail
from django.conf import settings
from django.db.models import fields
from .models import Question, Theme, Attempt

class ContactForm(forms.Form):
    name = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder': 'Nome'}))
    email = forms.EmailField(label='',widget=forms.TextInput(attrs={'placeholder': 'Email'}))
    message = forms.CharField(label='', widget=forms.Textarea(attrs={'cols': '40', 'rows': '4', 'placeholder': 'Mensagem'}))

    def send_mail(self):      
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        message = self.cleaned_data['message']
        message = 'Nome: {0}\nE-mail:{1}\n{2}'.format(name, email, message)
        send_mail(
            'Contato Projeto Anki-Univesp', message, settings.DEFAULT_FROM_EMAIL,
            [settings.DEFAULT_FROM_EMAIL]       
        )


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['description', 'answer', 'theme','public', 'user']

class ThemeForm(forms.ModelForm):
    class Meta:
        model = Theme
        fields = ['description', 'category', 'user']

class AttemptForm(forms.ModelForm):
    class Meta:
        model = Attempt
        fields = ['attempt_number', 'question', 'difficult', 'got_it_right', 'user']        

# class AttemptForm(forms.Form):
#     attempt_number = forms.IntegerField(label='Tentativa')
#     got_it_right = forms.BooleanField(label='acertou')
#     difficult = forms.IntegerField(label='dificuldade')
#     question = forms.ChoiceField(label='questão')
#     user = forms.CharField(label='usuario')

core/views.py
import asyncio
from unicodedata import category
from django.db import models
from django.shortcuts import redirect, render
from django.http import HttpResponse, JsonResponse
from .forms import AttemptForm, ContactForm , QuestionForm, ThemeForm
from django.core.mail import send_mail
from django.conf import settings
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import View, TemplateView, CreateView, DetailView, ListView
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from .models import Question, Theme, Attempt, Category
from Include import TextToSpeachConverter
from django.utils.encoding import uri_to_iri
import urllib

User = get_user_model()

class IndexView(TemplateView):
    template_name = 'index.html'
index = IndexView.as_view()


@login_required
def contact(request):
    success = False        
    form = ContactForm(request.POST or None)
    if form.is_valid():     
        form.send_mail()
        success = True
        form = ContactForm()

    context = {
        'form': form,
        'success': success
    }
    return render(request, 'contact.html', context)

def help(request):
    return render(request, 'help.html')

def file(request):
    return render(request, 'file.html')

def project(request):
    user  = request.user
    user_id = user.id
    current_user= User.objects.get(id=user_id)
    user_themes = current_user.theme_set.all()
    return render(request, 'project.html', {'themes': user_themes})

##Classe para acesso as informações da tabela Theme
# class ThemeListView(ListView):
#     model = Theme

# class ThemeDetailView(DetailView):
#     model = Theme

def list_theme(request):
    themes = Theme.objects.all()
    user  = request.user
    user_id = user.id
    current_user= User.objects.get(id=user_id)
    user_themes = current_user.theme_set.all()
    return render(request, 'themes.html', {'themes': user_themes})


def create_theme(request):
    form = ThemeForm(request.POST or None)
    user  = request.user
    user_id = user.id
    form.initial["user"] = user_id
    if form.is_valid():
        form.initial["user"] = user_id
        form.save()
        return redirect('list_theme')

    return render(request, 'themes-form.html', {'form': form})


def update_theme(request, id):
    theme = Theme.objects.get(id=id)
    form = ThemeForm(request.POST or None, instance=theme)
    user  = request.user
    user_id = user.id
    form.initial["user"] = user_id
    if form.is_valid():
        form.initial["user"] = user_id
        form.save()
        return redirect('list_theme')

    return render(request, 'themes-form.html', {'form': form, 'theme': theme})


def delete_theme(request, id):
    theme = Theme.objects.get(id=id)
    if request.method == 'POST':
        theme.delete()
        return redirect('list_theme')

    return render(request, 'theme-delete-form.html', {'theme': theme})


##Classe para acesso as informações da tabela Question
# class QuestionListView(ListView):
#     model = Question

# class QuestionDetailView(DetailView):
#     model = Question

def list_question(request):
    questions = Question.objects.all()
    user  = request.user
    user_id = user.id
    current_user= User.objects.get(id=user_id)
    user_questions = current_user.question_set.all()
    return render(request, 'questions.html', {'questions': user_questions})


def create_question(request):
    form = QuestionForm(request.POST or None)
    user  = request.user
    user_id = user.id
    form.initial["user"] = user_id
    if form.is_valid():
        form.initial["user"] = user_id
        form.save()
        return redirect('core:list_question')

    return render(request, 'questions-form.html', {'form': form})


def update_question(request, id):
    question = Question.objects.get(id=id)
    form = QuestionForm(request.POST or None, instance=question)
    user  = request.user
    user_id = user.id
    form.initial["user"] = user_id
    if form.is_valid():
        form.initial["user"] = user_id
        form.save()
        return redirect('core:list_question')

    return render(request, 'questions-form.html', {'form': form, 'question': question})


def delete_question(request, id):
    question = Question.objects.get(id=id)

    if request.method == 'POST':
        question.delete()
        return redirect('core:list_question')

    return render(request, 'question-delete-form.html', {'question': question})

##Classe para acesso as informações da tabela Attempt
# class AttemptListView(ListView):
#     model = Attempt

# class AttemptDetailView(DetailView):
#     model = Attempt

def list_attempt(request):
    questionCount = 0
    user  = request.user
    user_id = user.id
    current_user = User.objects.get(id=user_id)
    # attempts = Attempt.objects.filter(attempt_number=1,user=user_id)
    lastAttempt = current_user.attempt_set.order_by('-attempt_number')[0]
    attempts = Attempt.objects.filter(attempt_number=lastAttempt.attempt_number,user=user_id)
    # Convert = TextToSpeachConverter.TextToSpeachConverterPyttsx3()
    Convert = TextToSpeachConverter.TextToSpeachConverterGtts()

    # attempts = AttemptForm(request.POST or None, instance=antes)
    if request.POST:
        for value in request.POST:

            if (value != 'csrfmiddlewaretoken'):
                x = value.split("_")
                id = x[1]
                updateAttempt = Attempt.objects.get(id=id)
                #Ao salvar (finalizar a tentativa) fala a pergunta e as respostas.
                #Convert.ConvertAndPlay('Pergunta: ' + updateAttempt.question.description)
                #Convert.ConvertAndPlay('Resposta: ' + updateAttempt.question.answer)
             
                if (value == 'got-it-right_'+id):
                    updateAttempt.got_it_right = 1
                    updateAttempt.save()
                if (value == 'difficult_'+id):
                    updateAttempt.difficult = int(request.POST[value])
                    updateAttempt.save()

        return render(request, 'alert.html', {'no_record_check': 1})

    # Falar as perguntas geradas
    # for attempt in attempts:
    #     Convert.ConvertAndPlay('Pergunta ' + str(questionCount) + ':' +  attempt.question.description)
    #     questionCount += 1

    return render(request, 'attempts.html', {'attempts': attempts})


def create_attempt(request):
    user  = request.user
    user_id = user.id

    current_user = User.objects.get(id=user_id)
    user_themes = current_user.theme_set.all()
    categories = Category.objects.all()
    if request.POST:
        quantidade_select = request.POST['quantidade_perguntas']
        themeId = request.POST['decks']
        categoryId = request.POST['categoria']
        publicQuestionsOn = 'aceita_publica' in request.POST
        theme = Theme.objects.get(id=themeId)
        themeCategory = Theme.objects.filter(category = categoryId)
        
        #verifica quantas tentativas (quiz) já foram geradas para este usuário, para pegar o valor da nova tentativa.
        if current_user.attempt_set.count() > 0:
            lastAttempt = current_user.attempt_set.order_by('-attempt_number')[0]
            if lastAttempt.attempt_number :
                thisAttempt = lastAttempt.attempt_number + 1
        else:
            thisAttempt = 1

        #Verifica se no formulário o usuário marcou que irá usar as perguntas publicas para querar seu quiz de estudo
        if publicQuestionsOn:
            questions = current_user.question_set.all().filter(theme=theme).order_by('?') | Question.objects.filter(public = 1).filter(theme__in=themeCategory).order_by('?')
            questions = questions.order_by('?')[:int(quantidade_select)]
        else:
            questions = current_user.question_set.all().filter(theme=theme).order_by('?')[:int(quantidade_select)]
        count = 0
        length = questions.count()
        if length <= 0:
            return render(request,'alert.html', {'no_record_check': 0})       
        
        for question in questions:
            attempt = Attempt(attempt_number = int(thisAttempt), got_it_right=0 , difficult=0,question=question, user = current_user)
            attempt.save()
            count += 1
            if count == length:
                return redirect('list_attempt') 

    return render(request, 'create_attempts.html', {'themes': user_themes, 'categories': categories})

def readText(request):
   # print (request.GET)
    decodeTextUrl = urllib.parse.unquote(str(request.GET['text']))
    # Convert = TextToSpeachConverter.TextToSpeachConverterPyttsx3()
    Convert = TextToSpeachConverter.TextToSpeachConverterGtts()
    #print('----------------------------+++++++++------------------')
    #print(urllib.parse.unquote(str(request.GET['text'])))
    Convert.ConvertAndPlay(decodeTextUrl)
    data={'valor':'teste'}
    return JsonResponse(data)

core/templates/alert.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
    Realizar tentativa | {{ block.super }}
{% endblock %}
{% block container %}

<div>
    <br>
    <br>
    {% if no_record_check > 0 %}
        <div class="alert alert-success">
            <strong>Parabens processo concluido </strong>
        </div>
    {% else %}
        <div class="alert alert-warning">
            <strong> Não há nenhum Card cadastrado. Gentileza cadastre algum card. </strong>
        </div>
    {% endif %}
</div>

<div><a href="{% url 'index' %}"><button class="btn btn-primary">Página Principal</button></a></div>

{% endblock %}

core/templates/attempts.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
    Realizar tentativa | {{ block.super }}
{% endblock %}
{% block container %}

<div class="container">

  <div class="row mensage_questions">
    <div class="col px-0">
      <h5 class>Foi gerado o teste com base em sua escolha, responda e escolha a sua avaliação para cada questão.</h5>
    </div>
  </div>
   
    <form method="POST">
        {% csrf_token %}
        <!-- {{ form }} -->

        {% for attempt in attempts %}
          <div class="row">
            <div class="col-sm-4 p-2">            
              <a class="btn btn-primary element_for_read form-control" onclick="checkAnswer('{{attempt.question.answer}}', 'resposta_{{attempt.id}}', 'got-it-right_{{attempt.id}}')" data-toggle="collapse" href="#{{attempt.id}}" role="button" aria-expanded="false" aria-controls="{{attempt.id}}">
                {{attempt.question.description}}
              </a>      
            </div>        
            <div class="col-sm-8 p-2">
              <input type="text" class="form-control"  id="resposta_{{attempt.id}}" placeholder="Reposta (opcional)">
            </div>
          </div>    

        <div class="form-group">
          <div class="card collapse" name="{{attempt.id}}" id="{{attempt.id}}">
            <div class="card card-body">
              <label class="form-check-label element_for_read" for="answer_{{attempt.id}}">Resposta</label>
              <div class="alert alert-success element_for_read" role="alert">
                {{attempt.question.answer}}
              </div>
              
              <div class="card-footer text-muted">
                <div class="form-check">
                  <input type="checkbox" class="form-check-input" name="got-it-right_{{attempt.id}}" id="got-it-right_{{attempt.id}}">
                  <label class="form-check-label element_for_read" for="got-it-right_{{attempt.id}}">Acertei</label>
                </div>
                
                <div class="form-group">
                  <label for="difficult_{{attempt.id}}" class="element_for_read">Qual a difiuldade da pergunta?</label>
                  <select class="form-control element_for_read" name="difficult_{{attempt.id}}" id="difficult_{{attempt.id}}">
                    <option value="1">Fácil</option>
                    <option value="2">Médio</option>
                    <option value="3">Dificil</option>
                  </select>
                </div>
              </div>
            </div>
          </div>
        </div>
        <hr>
    
        {% endfor %}
        <div class="form-group">
            <button type="submit" class="btn btn-success">Concluir</button>
        </div>
        
    </form>
</div>
{% endblock %}
<script> 
  $('.carousel').carousel()
</script>

core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>{% block title %}Projeto SEREI{% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <link rel="icon" type="image/x-icon" href="{% static 'assets\images\fav_icon.png' %}">
	<link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}" media="screen" />
	<link rel="stylesheet" href="{% static 'assets/css/custom.min.css' %}" media="screen" /> 
  <link rel="stylesheet" href=https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css>
  <link rel="stylesheet" href="{% static 'assets/css/animate.css' %}">
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="{% url 'index' %}" class="navbar-brand">
            <img src="{% static 'assets/images/logo.png' %}" alt="Imagem não disponível" srcset="">
          </a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="{% url 'index' %}">Início</a>
            </li>  
            {% if user.is_authenticated %}
            <!-- <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="{% url 'file' %}" id="download">Editar<span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="download">
                <li><a href="{% url 'file' %}">Desfazer</a></li>                
              </ul>
            </li>                 -->
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="{% url 'file' %}" id="download">Cadastros <span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="download">
                <li><a href="{% url 'core:list_question' %}">Criar Baralho</a></li>
                <li><a href="{% url 'core:list_theme' %}">Temas dos baralhos</a></li>
              </ul>
            </li>
            {% endif %}
            <!-- <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="{% url 'file' %}" id="download">Ajuda<span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="download">
                <li><a href="{% url 'file' %}">Guia</a></li>
                <li><a href="{% url 'file' %}">Contribua Conosco</a></li>
                <li><a href="{% url 'file' %}">Sobre</a></li>                
              </ul>
            </li>  -->
              <li>
                <a href="{% url 'contact' %}">Contato</a>
             </li>   
            </ul>
            <ul class="nav navbar-nav navbar-right">         
              <li class=""> <button type="button" class="btn btn-primary alignment-center btn_sound"  id="sound-button" name="sound-button"> <span class="glyphicon glyphicon-volume-up" aria-hidden="true"> </span> </button> </li>
              {% if user.is_authenticated %}
              <li><a href="{% url 'logout' %}">Sair</a></li>
              {% else %}
              <li><a href="{% url 'login' %}">Entrar</a></li>               
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="{% url 'accounts:register' %}" id="download">Cadastro<span class="caret"></span></a>
                <ul class="dropdown-menu" aria-labelledby="download">
                  <li><a href="{% url 'accounts:register' %}">Cadastrar usuário</a></li>                  
                  <li><a href="{% url 'accounts:index' %}">Alterar dados usuário</a></li>                  
                </ul>
              </li>             
              {% endif %}
            </ul>
        </div>
      </div>
    </div>    
    <div class="container margin-top">    
		{% block container %}{% endblock %}
		<footer class="navbar-default navbar-fixed-bottom fotter">
      <div class="container">
        <hr>
        <div class="row">
          <div class="col-sm-6">
            <ul class="list-unstyled">
              <li><a href="{% url 'index' %}">Início</a></li>			      
              <li><a href="{% url 'contact' %}">Contato</a></li>
              <!-- <li><a href="{% url 'file' %}">Preferências</a></li> -->
              <li><a href="{% url 'file' %}">Termos e Privacidade</a></li>    
            </ul>           
          </div> 
          <div class="col-sm-6 text-right"> 
            <a href="https://www.youtube.com/" class="social_media_icons_enabled"  target="_blank">
              <i class="fa-brands fa-youtube fa-2xl"></i>
             </a>
            <a href="#" class="social_media_icons_disabled" data-toggle="tooltip" data-placement="bottom" title="Em breve" target="_blank">
              <i class="fa-brands fa-facebook-square fa-2xl"></i>
            </a>      
            <a href="#" class="social_media_icons_disabled" data-toggle="tooltip" data-placement="bottom" title="Em breve" target="_blank">
                <i class="fa-brands fa-whatsapp fa-2xl"></i>
            </a>         
          </div>       
        </div>
      </div>
		</footer>
	</div>  
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
  <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets/js/custom.js' %}"></script>
</body>
</html>

core/templates/contact.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
    Contato | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
    {% if success %}
    <div class="alert alert-success animate__animated animate__fadeOut animate__delay-3s">
        Mensagem enviada com sucesso.
    </div>
    {% endif %}
    <div class="container">
      <h1 class="text-center">Fale conosco</h1>
      <div class="row">
        <div class="offset-3 col-6">
          <form class="form-horizontal" action="" method="POST">
            {% csrf_token%}
              <fieldset>
                  {% for field in form %}
                  <div class="form-group{% if field.errors %} has-error {% endif %}">
                    <div class="col-md-6 col-md-offset-3">
                      {% render_field field class='form-control' %}
                      {% for error in field.errors %}
                      <span class="help-block">{{ error }}</span>
                      {% endfor %}
                    </div>
                  </div>
      
                  {% endfor %}
                  
                  <div class="form-group">
                    <div class="col-md-6 col-md-offset-3">
                      <button type="submit" class="btn btn-primary">Enviar</button>
                    </div>
                  </div>
              </fieldset>
          </form>
        </div>
      </div>
    </div>
</div>
{% endblock %}

core/templates/questions-form.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
    Questões | {{ block.super }}
{% endblock %}
{% block container %}

<div>
    <h1>Novo/Alterar questão</h1>

    <form method="POST">
        {% csrf_token %}
        <!-- {{ form }} -->

        {% for field in form %}
            {% if field.label != 'Usuários'  %}
                <div class="form-group{% if field.errors %} has-error{% endif %}">
                <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
                    <div class="col-md-9">
                    
                            {% render_field field class="form-control" %}
                        
                        {% for error in field.errors %}
                        <span class="help-block">{{ error }}</span>
                        {% endfor %}
                    </div>
                </div>
            {% else %}
                {% render_field field class="hidden" %}
            {% endif %}
            
        {% endfor %}
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Salvar</button>
            {% if question %}
                <a href="{% url 'core:delete_question' question.id %}"> <button type="button" class="btn deletar" style="background-color:red; color:white">Deletar </button></a>
            {% endif %}
        </div>
        
    </form>



</div>
{% endblock %}

core/templates/questions.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
    Questões | {{ block.super }}
{% endblock %}
{% block container %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h1>Perguntas</h1>
        </div>
        <ul class="list-group">
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Pergunta</th>
                    <th scope="col">Tema</th>
                    <th scope="col">Pública</th>
                  </tr>
                </thead>
                <tbody>
            {% for question in questions %}
                  <tr>
                    <td><a href="{% url 'core:update_question' question.id %}">
                            <li class="list-group-item"> {{ question.description }}</li>
                        </a>
                    </td>
                    <td><li class="list-group-item"> {{ question.theme.description }}</li></td>
                    <!-- a função do jango  {{VALUE|yesno:"texto se true, texto se falsez texto caso nulo"}} 
                        pemite configurar respostas padronizadas para valores booleanos -->
                    <td><li class="list-group-item">  {{ question.public|yesno:"SIM,NO,MAYBE" }}   </li></td>
                  </tr>
                
                
            {% endfor %}
                </tbody>
            </table>
        </ul>

        <a href="{% url 'core:create_question' %}"> <button class="btn btn-primary" >  Nova Questão </button></a>
    </div>
</div>
{% endblock %}

core/templates/themes-form.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
    Temas | {{ block.super }}
{% endblock %}
{% block container %}
<div>
    <h1>Novo/Alterar Tema</h1>

    <form method="POST">
        {% csrf_token %}
         <!-- {{ form }} -->
         {% for field in form %}
            {% if field.label != 'User' %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
            <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
            <div class="col-md-9">
                {% render_field field class="form-control" %}
                {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
            </div>
            </div>
            {%else%}
                {% render_field field class="form-control hidden" %}
            {% endif %}
        
         {% endfor %}
        <div class="form-group">
            <button type="submit" class="btn btn-primary ">Salvar</button>
            {% if theme %}
            
                <a href="{% url 'core:delete_theme' theme.id %}"> <button type="button" class="btn deletar" style="background-color:red; color:white"> Deletar </button></a>
            {% endif %}
        </div>
    </form>
   
</div>
{% endblock %}